### ISSUE TITLE
Invalid Ruby code validates

### ISSUE THREAD

**Issue by simmel** [logstash-plugins/logstash-filter-ruby#43]
I'm in the process of migrating our config to 6.x and I found what I think is a bug.

It appears that Ruby code isn't "compiled" or otherwise validated until it's tries to run an event through it.

Config test should validate the Ruby code and it should be done during normal startup too.

With:
```
input {
  generator {
    count => 2
  }
}
filter {
  if [sequence] > 0 {
    ruby {
      code => "event['old'] = 2"
    }
  }
}
output {
  stdout {
    codec => rubydebug {}
  }
}
```
* config test should not pass
* logstash should FATAL before the first event is generated.

**Comment by jordansissel** [comment]
This is valid ruby: `event['old'] = 2`

I agree this is a bit confusing, though, this is a property of ruby that there are basically no compile-time checks and almost all errors are runtime errors. Even things like using a variable that doesn't exist -- this would be a compilation error in Java, C, etc, but is a runtime error in Ruby with no way to evaluate "Will this code execute?" without actually executing the code.

Back to your concern about validation. I don't know how we can provide validation here. A simple case like this may be validated by executing it, but because many things are runtime errors, it's unclear what is a programmer error and what is an expected exception.

In your specific case: `event['old']` is not right because the `event` object deprecated and removed the `[]` method many releases ago. This probably throws an exception, right?  But what about this code: `code => "raise 'Abort!'"` ? This will also throw an exception, but is it invalid code?

Because nearly everything is a runtime error, and we cannot divine the author's intent in, it may be very difficult to actually provide what you are asking for because we:

1) Can't always predict the runtime environment -- an empty event object might work, but an event object in production with data might throw an exception.
2) Can't easily infer what is an expected outcome vs a programmer error.
3) A simulated test to attempt validation might itself throw an exception where perhaps in production this may never fail.

I'm not sure how we can provide config-validation reporting here because I can't yet think of a way to generically validate user code without executing it, and some code may not fail 100% of the time, so it's unclear how to achieve validation when we cannot predict ways the code will fail.

At least in your scenario, this method `event[...]=` was removed and you get an error that tells you what correction to make:

```
[2018-02-11T16:08:16,609][ERROR][logstash.filters.ruby    ] Ruby exception occurred: Direct event field references (i.e. event['field'] = 'value') have been disabled in favor of using event get and set methods (e.g. event.set('field', 'value')). Please consult the Logstash 5.0 breaking changes documentation for more details.
```

---

Longer term, I strongly recommend using [the newer file-based scripts](https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html#_using_a_ruby_script_file)  feature. This feature allows you to [write tests](https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html#_testing_the_ruby_script) so that you can do your own custom validation. Per the docs, "The tests you define will run when the pipeline is created and will prevent it from starting if a test fails" -- This is basically what you want :)

You can read more about this feature on [this blog post](https://www.elastic.co/blog/moving-ruby-code-out-of-logstash-pipeline).

**Comment by simmel** [comment]
Thank you for your very detailed response!

I now see that I misread that documentation. I totally missed that logstash runs the tests *before* the pipeline starts!
