### ISSUE TITLE
script_params passing bools as strings

### ISSUE THREAD

**Issue by vbohata** [logstash-plugins/logstash-filter-ruby#53]
When passing boolean values in script_params, they are in fact passed to the external script as strings.

**Comment by yaauie** [comment]
Unfortunately, this is by design and something that cannot be fixed.

The logstash configuration language supports [`bareword`](https://github.com/elastic/logstash/blob/ccbfd8a9ae7045661afb7225e55602c72db34c57/logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop#L70-L73)s (unquoted alphanumeric strings) and does not have keywords; when it encounters the value in  `param => false`, the `f` `a` `l` `s` `e` sequence is interpreted as an unquoted string just as it would interpret `param => fubar` to have a value for `param` of `fubar`.
